# Generated by Django 5.0.6 on 2024-06-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        ('vols_depart_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.clients')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vols_depart_app.flightdeparture')),
                ('prix_ticket', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
