# Generated by Django 5.0.6 on 2024-06-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
        ('vols_depart_app', '0002_rename_origin_flightdeparture_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vols_depart_app.flightdeparture'),
        ),
    ]
