# Generated by Django 5.0.6 on 2024-06-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='flight_id',
            new_name='flight',
        ),
    ]
