# Generated by Django 5.0 on 2024-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_reservation_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
