# Generated by Django 5.0.6 on 2024-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0003_reservation_created_at_reservation_prix_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='prix_ticket',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
