# Generated by Django 5.0.6 on 2024-06-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0004_alter_reservation_prix_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
    ]
