# Generated by Django 5.0.6 on 2024-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0005_remove_reservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='prix_ticket',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
