# Generated by Django 5.0.6 on 2024-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=255)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
