# Generated by Django 5.0 on 2024-06-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols_depart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdeparture',
            name='departure_airport',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
