# Generated by Django 5.0.6 on 2024-06-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vols_depart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightdeparture',
            old_name='origin',
            new_name='destination',
        ),
    ]
