# Generated by Django 5.0.6 on 2024-06-13 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols_depart_app', '0002_rename_origin_flightdeparture_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdeparture',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
    ]
