# Generated by Django 5.0 on 2024-06-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vols_depart_app', '0002_flightdeparture_departure_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdeparture',
            name='departure_airport',
        ),
    ]
