# Generated by Django 5.0.6 on 2024-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols_depart_app', '0003_flightdeparture_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdeparture',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
