# Utilisez l'image officielle de MariaDB comme base
FROM mariadb:latest

# Définit le nom de la base de données
ENV MYSQL_DATABASE aeroport_db

# Expose le port 3306 pour la communication avec la base de données
EXPOSE 3306
