# Generated by Django 5.0 on 2024-06-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement_app', '0002_paiement_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='client_email',
        ),
    ]
