# Generated by Django 5.0 on 2024-06-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement_app', '0003_remove_paiement_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='client_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
